# -*- coding: utf-8 -*-
"""Actions restantes au 30 sept. 2026, 9 h.
owner_status : 'confirmé' (la personne est nommée dans le dossier) ou 'proposé' (c'est notre proposition).
kind : 'engagement documenté' (l'action existe dans le dossier) ou 'recommandation' (c'est notre équipe qui la propose)."""

ACTIONS = [
 {"id": "A-01", "condition": 1, "priority": "Bloquant go-live",
  "title": "Refaire le test de SEC-210 (le journal doit montrer l'objet et le résultat de l'export CSV), puis donner ou refuser l'acceptation sécurité",
  "owner": "Sophie Lambert (sécurité)", "owner_status": "confirmé", "kind": "engagement documenté",
  "due": "À confirmer (re-test « planifié » le 26 sept., sans date; à faire avant le 22 oct.)",
  "evidence": [["SEC-210", 24, 25, "commentaires du 19 sept. 14:05 et du 26 sept. 15:40"], ["M06_Transcript_Comite_26sept", 7, 11, "10:02 et 10:09"], ["Registre_Risques_29sept", 4, 4, "R-02"]],
  "note": "Vérifier aussi le journal « en situation réelle », comme Sophie l'a demandé le 27 août (M03, ligne 11). Ne pas fermer le ticket sur la seule base des tests automatisés de Boréal."},
 {"id": "A-02", "condition": 2, "priority": "Bloquant go-live",
  "title": "Livrer le correctif ACC-303 (le focus clavier bloqué dans la fenêtre « Modifier le dossier ») dans la prochaine build",
  "owner": "Boréal Numérique (Julien Moreau)", "owner_status": "confirmé", "kind": "engagement documenté",
  "due": "À confirmer (« prochaine build », date non documentée)",
  "evidence": [["M06_Transcript_Comite_26sept", 15, 15, "10:12"], ["ACC-303", 15, 16, "18 sept. 09:50 et 26 sept. 11:03"]],
  "note": "Cause trouvée par Boréal : la liste des éléments qui peuvent recevoir le focus est incomplète dans le composant de fenêtre."},
 {"id": "A-03", "condition": 2, "priority": "Bloquant go-live",
  "title": "Retester ACC-303 au clavier (Chrome et Edge, Tab jusqu'à « Enregistrer ») et fermer le ticket",
  "owner": "Mélissa Gagnon (QA et accessibilité)", "owner_status": "confirmé", "kind": "engagement documenté",
  "due": "À confirmer (après la build corrective; avant le 22 oct.)",
  "evidence": [["ACC-303", 6, 6, "Statut OUVERT"], ["Registre_Risques_29sept", 6, 6, "R-04 : Fermer ACC-303"], ["M06_Transcript_Comite_26sept", 9, 13, "10:05 à 10:10"]],
  "note": "Il faut une validation QA : une correction annoncée par le fournisseur ne ferme pas le ticket."},
 {"id": "A-04", "condition": 3, "priority": "Bloquant go-live",
  "title": "Livrer le runbook final : écrire l'étape 4 « Procédure de retour arrière » (TODO) et l'étape 5 « Validation fonctionnelle post-déploiement » (À compléter). Une autre personne doit pouvoir l'exécuter sans l'équipe projet",
  "owner": "Boréal Numérique (équipe ops relancée par Julien)", "owner_status": "confirmé", "kind": "engagement documenté",
  "due": "À confirmer (version finale toujours attendue le 29 sept.; Olivier la veut « quelques jours » avant la mise en production)",
  "evidence": [["OPS-601_runbook", 6, 7, "capture du 25 sept., étapes 4 et 5"], ["OPS-601", 14, 16, "25, 26 et 29 sept."], ["M06_Transcript_Comite_26sept", 15, 15, "10:12 : « je relance notre équipe ops »"], ["M04_Transcript_Comite_direction_10sept", 12, 12, "15:12"]],
  "note": "Le dossier ne dit pas clairement que c'est Boréal qui rédige le runbook. On le déduit de « je relance notre équipe ops ». À confirmer avec Olivier."},
 {"id": "A-05", "condition": 3, "priority": "Bloquant go-live",
  "title": "Approuver le runbook et donner le go exploitation",
  "owner": "Olivier Côté (exploitation)", "owner_status": "confirmé", "kind": "engagement documenté",
  "due": "À confirmer (avant le 22 oct.)",
  "evidence": [["M06_Transcript_Comite_26sept", 10, 10, "10:07"], ["Registre_Risques_29sept", 5, 5, "R-03"], ["Note_transition_Elodie_16sept", 10, 10, "« obtenir le go sécurité et exploitation avant production »"]],
  "note": ""},
 {"id": "A-06", "condition": None, "priority": "Haute (finances)",
  "title": "Régler INV-003 : ne pas payer les 18 000 $ « Optimisation interface mobile - CR-04 »; répondre à Finances; demander à Boréal une facture corrigée (36 000 $) ou une note de crédit; payer le jalon 3 seulement quand sa livraison est confirmée",
  "owner": "Nicolas Perron (chargé de projet) avec Amélie Fortin (Finances)", "owner_status": "proposé", "kind": "recommandation",
  "due": "À confirmer (facture du 22 sept., retenue depuis le 23 sept.)",
  "evidence": [["E07_Facture_003_question", 9, 11, "question de Finances, sans réponse dans le dossier"], ["E10_Fonction_mobile", 11, 11, "« Aucune dépense liée à CR-04 ne doit être engagée ou facturée »"], ["INV-003", 19, 23, "lignes jalon 3, CR-04 et total"], ["CONTRAT_Boreal_NOVA", 22, 24, "Gestion des changements"]],
  "note": "Documenté : l'interdiction de facturer CR-04 (E10). Recommandation de notre équipe : la façon de régulariser (facture corrigée ou paiement partiel) et la vérification du jalon 3."},
 {"id": "A-07", "condition": None, "priority": "Haute (gouvernance)",
  "title": "Publier un plan projet v4 : P-06 au 22 octobre, recaler P-04 (tests intégrés) et P-05 (préparation exploitation), responsable Nicolas",
  "owner": "Nicolas Perron", "owner_status": "proposé", "kind": "engagement documenté (la mise à jour est demandée), responsable proposé",
  "due": "À confirmer",
  "evidence": [["M04_Transcript_Comite_direction_10sept", 23, 23, "« On doit mettre les plans et communications à jour »"], ["Note_transition_Elodie_16sept", 7, 7, "« faire mettre à jour la date dans tous les plans »"], ["Plan_Projet_NOVA_v3_12sept", 6, 8, "P-04, P-05, P-06"], ["Teams_15sept_ProjetNOVA", 5, 5, "plan non corrigé"]],
  "note": "La mise à jour est un engagement du comité. Nommer Nicolas est notre proposition (il est chargé de projet et responsable de P-06)."},
 {"id": "A-08", "condition": None, "priority": "Moyenne (gouvernance)",
  "title": "Mettre à jour le registre de risques : fermer R-01 (INT-101 fermé le 17 sept.); ajouter le risque « glissement après le 31 octobre (fin du contrat) » et le risque « facture contestée »",
  "owner": "Nicolas Perron (registre) et Marc Gervais (propriétaire de R-01)", "owner_status": "proposé", "kind": "recommandation",
  "due": "À confirmer",
  "evidence": [["Registre_Risques_29sept", 3, 3, "R-01 ouvert, suivi au 9 sept."], ["INT-101", 18, 18, "fermé le 17 sept."], ["CONTRAT_Boreal_NOVA", 16, 16, "période jusqu'au 31 octobre"]],
  "note": "Les deux nouveaux risques sont des recommandations de notre équipe. Ils ne sont pas dans le dossier."},
 {"id": "A-09", "condition": None, "priority": "Haute (communication)",
  "title": "Corriger le brouillon d'Alex : ne pas écrire « au vert » ni « sécurité et accessibilité complétées »; présenter le 22 octobre comme une cible sous conditions",
  "owner": "Alex Deschamps, validé par Nicolas Perron", "owner_status": "proposé", "kind": "engagement documenté (consigne E09), rédaction proposée",
  "due": "À confirmer (brouillon du 21 sept. toujours sans réponse)",
  "evidence": [["E11_Communication_statut", 11, 13, "le brouillon"], ["E09_Rappel_mise_en_production", 13, 13, "« ne pas communiquer le 22 comme un go garanti »"], ["Rapport_Statut_21sept", 10, 12, "statuts VERT contredits"]],
  "note": "Pas de réponse de Nicolas à Alex dans le dossier. E09 (27 sept., à toute l'équipe) sert de consigne."},
 {"id": "A-10", "condition": None, "priority": "Moyenne (gouvernance)",
  "title": "Corriger ou annoter le rapport de statut du 21 sept. (Sécurité et Accessibilité ne sont pas VERT; Budget : facture contestée) et trouver son auteur",
  "owner": "Nicolas Perron", "owner_status": "proposé", "kind": "recommandation",
  "due": "À confirmer",
  "evidence": [["Rapport_Statut_21sept", 6, 18, "synthèse et commentaire de gestion"], ["SEC-210", 25, 25, "EN VALIDATION"], ["ACC-303", 6, 6, "OUVERT"]],
  "note": "L'auteur du rapport n'est pas indiqué dans le dossier."},
 {"id": "A-11", "condition": None, "priority": "Haute (gouvernance)",
  "title": "Planifier le go/no-go formel avant le 22 octobre (vérifier les trois conditions) et publier le compte rendu du comité du 26 sept.",
  "owner": "Nicolas Perron", "owner_status": "proposé", "kind": "recommandation (le compte rendu du 26 sept. est un engagement documenté)",
  "due": "À confirmer (avant le 22 oct.)",
  "evidence": [["M06_Transcript_Comite_26sept", 25, 25, "10:30 : « Je publie le compte rendu »"], ["E09_Rappel_mise_en_production", 11, 13, "conditions restantes"]],
  "note": "Aucune réunion de go/no-go n'est prévue dans le dossier."},
 {"id": "A-12", "condition": None, "priority": "Basse (phase 2)",
  "title": "Traiter CR-04 (optimisation mobile avancée, 18 000 $) pour la phase 2 : décision formelle d'approbation ou de refus, avec l'instance qui décide et la date",
  "owner": "Nicolas Perron et comité de projet", "owner_status": "proposé", "kind": "recommandation",
  "due": "À confirmer (phase 2)",
  "evidence": [["Decision_Portee_Phase2", 3, 6, "reporté en phase 2"], ["CR-04_Optimisation_mobile_BROUILLON", 8, 8, "BROUILLON - APPROBATION REQUISE"]],
  "note": "Boréal a déjà « commencé à regarder » des ajustements (M06 10:24). Rappeler qu'aucun travail CR-04 n'est facturable."},
 {"id": "A-13", "condition": None, "priority": "Moyenne (contrat)",
  "title": "Vérifier la marge du contrat : il court jusqu'au 31 octobre. Si le 22 octobre glisse, prévoir un avenant (dates) et surveiller le plafond de 204 000 $",
  "owner": "Nicolas Perron avec Finances", "owner_status": "proposé", "kind": "recommandation",
  "due": "À confirmer",
  "evidence": [["CONTRAT_Boreal_NOVA", 12, 16, "montant et période"], ["M04_Transcript_Comite_direction_10sept", 15, 15, "« le contrat court jusqu'à fin octobre »"]],
  "note": ""},
]

# Engagements documentés déjà tenus (fermés). Gardés pour la traçabilité.
CLOSED_COMMITMENTS = [
 {"title": "Boréal : fournir le premier schéma d'architecture", "src": "M01_CR_Demarrage_07juillet", "lines": [15,15], "closed": "18 juil. (v1), remplacé par la v2 le 25 août"},
 {"title": "Boréal : migrer les ressources vers Canada Central; architecture : publier le schéma v2", "src": "ADR-007_Localisation_donnees", "lines": [13,15], "closed": "26 et 27 août (E03, M03)"},
 {"title": "Boréal : build de stabilisation début septembre", "src": "M03_CR_Comite_27aout", "lines": [13,13], "closed": "Build déclarée stable au comité du 26 sept. (M06 10:01). Date de livraison non documentée"},
 {"title": "Marc : suivre le connecteur interne jusqu'à la fermeture formelle (INT-101)", "src": "Note_transition_Elodie_16sept", "lines": [9,9], "closed": "17 sept. (INT-101, E12)"},
 {"title": "Camille : corriger les doublons de migration (DATA-401)", "src": "DATA-401", "lines": [16,19], "closed": "9 sept."},
 {"title": "Dév : corriger la lenteur de la recherche (PERF-501)", "src": "PERF-501", "lines": [15,16], "closed": "7 sept."},
 {"title": "Boréal : corriger les étiquettes et le contraste (ACC-301, ACC-302)", "src": "ACC-302", "lines": [15,16], "closed": "15 et 20 août (validés par Mélissa)"},
]
