# -*- coding: utf-8 -*-
"""Q06 à Q10."""

QUESTIONS_B = [
 {
  "id": "Q06",
  "question": "Quel problème présente INV-003? Précisez le montant concerné et le traitement à prévoir.",
  "answer": "INV-003 (facture Boréal du 22 septembre 2026, total 54 000 $, statut « En validation ») contient une ligne « Optimisation interface mobile - CR-04 » de 18 000 $. Or CR-04 est un brouillon qui n'a jamais été approuvé (aucun numéro d'approbation, aucune signature). Le comité du 10 septembre n'a pris « aucune décision de dépense ». Le 24 septembre, Nicolas Perron a écrit que CR-04 est reporté en phase 2 et qu'aucune dépense liée ne doit être engagée ni facturée. Le contrat interdit de facturer un travail hors portée sans demande de changement écrite et approuvée. Montant concerné : 18 000 $. L'autre ligne, « Développement phase 1 - jalon 3 » (36 000 $), fait partie de la portée. Traitement à prévoir : ne pas payer les 18 000 $; contester la ligne auprès de Boréal et demander une facture corrigée (ou une note de crédit) qui ramène INV-003 à 36 000 $; répondre à Amélie Fortin (Finances), qui retient la facture; payer le jalon 3 seulement quand sa livraison est confirmée.",
  "nuance": [
    "Ce qui est documenté : « Aucune dépense liée à CR-04 ne doit être engagée ou facturée » (E10, décision de portée). Ce qui n'est pas documenté : la façon de régulariser (facture corrigée ou paiement partiel). C'est une RECOMMANDATION de notre équipe, à confirmer par Nicolas et Finances.",
    "Boréal avait été prévenu avant même la facture. Nicolas a rappelé sur Teams le 22 sept. que le package CR-04 à 18 k n'est pas approuvé. Au comité du 26 sept. : « Regarder, oui. Facturer du CR-04, non. »",
    "Le dossier ne contient pas de réponse de Nicolas à Amélie (E07), ni de preuve que le jalon 3 est livré. À vérifier avant de payer.",
  ],
  "evidence": [
    {"src": "INV-003", "loc": "page 1 : Date 2026-09-22, Statut « En validation », ligne « Optimisation interface mobile - CR-04 » 18 000 $, TOTAL 54 000 $", "lines": [12,26], "quote": "Statut En validation … Développement phase 1 - jalon 3 36 000 $ … Optimisation interface mobile - CR-04 18 000 $ … TOTAL 54 000 $ … La référence CR-04 apparaît sur la ligne mobile.", "note": "La facture elle-même."},
    {"src": "E07_Facture_003_question", "loc": "courriel du 23 sept. 10:18, lignes 9 à 11", "lines": [9,11], "quote": "Il y a une ligne de 18 000 $ « Optimisation interface mobile - CR-04 ». Peux-tu me transmettre l'approbation correspondante? Je trouve un brouillon de CR-04, mais rien qui indique qu'il a été approuvé.", "note": "Finances retient la facture. La pièce jointe est le même fichier INV-003.pdf : ce n'est pas une deuxième preuve."},
    {"src": "CR-04_Optimisation_mobile_BROUILLON", "loc": "page 1, Statut « BROUILLON - APPROBATION REQUISE »; note finale", "lines": [6,15], "quote": "Statut BROUILLON - APPROBATION REQUISE […] Aucun numéro d'approbation ni signature de comité n'est présent dans ce document.", "note": "Pas d'approbation."},
    {"src": "E10_Fonction_mobile", "loc": "courriel du 24 sept. 13:42, lignes 9 à 11", "lines": [9,11], "quote": "les optimisations mobiles avancées proposées dans CR-04 ne font pas partie de la phase 1 approuvée. Nous les reportons à la phase 2. Aucune dépense liée à CR-04 ne doit être engagée ou facturée sans nouvelle approbation.", "note": "Position officielle du chargé de projet, envoyée à Boréal et à Finances."},
    {"src": "CONTRAT_Boreal_NOVA", "loc": "page 1, section « Gestion des changements »", "lines": [22,24], "quote": "Tout travail hors portée doit faire l'objet d'une demande de changement écrite et approuvée avant exécution et facturation.", "note": "La règle du contrat qui justifie le refus."},
    {"src": "M04_Transcript_Comite_direction_10sept", "loc": "lignes 30 à 35 (15:34 à 15:40)", "lines": [30,35], "quote": "autour de 18 000 $ […] Pas selon la portée actuelle. On va traiter ça séparément, aucune approbation aujourd'hui. […] Mobile : aucune décision de dépense.", "note": "Le comité n'a rien approuvé."},
    {"src": "M06_Transcript_Comite_26sept", "loc": "lignes 22 à 24 (10:24 à 10:27)", "lines": [22,24], "quote": "Regarder, oui. Facturer du CR-04, non. Il n'est pas approuvé.", "note": "Rappel au fournisseur après la facture."},
  ],
  "cross": "Facture, courriel de Finances, CR-04 (brouillon), courriel E10, contrat et transcriptions (M04, M06).",
  "uncertainty": "Pas de trace d'une note de crédit, d'une facture corrigée ni d'une réponse écrite à Finances. Livraison du jalon 3 non documentée.",
 },
 {
  "id": "Q07",
  "question": "Où les données de production doivent-elles être hébergées? Quelle preuve confirme la mise en œuvre?",
  "answer": "Au Canada, dans la région Canada Central. La décision a été prise en atelier d'architecture le 23 juillet 2026 (Élodie, Marc, Sophie et Julien d'accord), à la demande de la sécurité (Sophie Lambert). Elle est formalisée dans l'ADR-007 (statut « Acceptée »). L'architecture v1 (East US, 18 juillet) est remplacée sur ce point. Preuves que c'est fait : 1) courriel de Boréal du 26 août 9 h 05 : « migration des ressources […] vers Canada Central est complétée », test de déploiement et de connectivité la veille sans blocage, schéma v2 joint; 2) schéma Architecture_NOVA_v2 (25 août, « Version révisée après ADR-007 », Données : Canada Central); 3) comité du 27 août : migration « déclarée terminée par Boréal et vérifiée par l'équipe architecture »; 4) plan projet : activité P-02 Architecture « Terminé », note « Migration Canada requise ».",
  "nuance": [
    "La pièce jointe de E03 est le même fichier que 06_Architecture_et_decisions/Architecture_NOVA_v2.pdf (même empreinte). Il ne faut pas la compter deux fois. La vraie confirmation indépendante, c'est le comité du 27 août (vérification côté client).",
    "L'ADR-007 demandait une validation technique avant les tests de production. Le compte rendu du 27 août en tient lieu (« vérifiée par l'équipe architecture »). Il n'y a pas de rapport de validation détaillé dans le dossier.",
    "Le schéma v2 est un dessin simplifié. Il ne liste pas les ressources migrées.",
  ],
  "evidence": [
    {"src": "ADR-007_Localisation_donnees", "loc": "lignes 3, 4, 9 et 10 (Décision)", "lines": [9,10], "quote": "L'environnement de production de NOVA sera déployé dans **Canada Central**. L'architecture v1 doit être considérée comme remplacée sur ce point.", "note": "La décision formelle (acceptée le 23 juillet)."},
    {"src": "M02_Transcript_Architecture_23juillet", "loc": "lignes 11 à 17 (09:06 à 09:12)", "lines": [11,17], "quote": "Les données de production NOVA doivent demeurer au Canada. […] Donc on tranche Canada Central? Marc : Oui. Sophie : Oui. Julien : Oui de notre côté. […] La v1 devient donc obsolète pour la localisation des données.", "note": "D'où vient l'exigence, et l'accord de tous."},
    {"src": "E03_Confirmation_Canada_Central", "loc": "courriel du 26 août 09:05, lignes 9 à 11", "lines": [9,11], "quote": "La migration des ressources prévues pour NOVA vers Canada Central est complétée. […] test de déploiement et de connectivité hier soir. Aucun blocage identifié.", "note": "Le fournisseur dit que c'est fait."},
    {"src": "M03_CR_Comite_27aout", "loc": "ligne 5", "lines": [5,5], "quote": "La migration de l'architecture vers Canada Central est déclarée terminée par Boréal et vérifiée par l'équipe architecture.", "note": "Vérification côté client (autre source)."},
    {"src": "Architecture_NOVA_v2", "loc": "page 1 : titre « v2 - 25 août 2026 », « Version révisée après ADR-007 », bloc « Données / Canada Central »", "lines": [1,7], "quote": "Architecture NOVA - v2 - 25 août 2026 / Version révisée après ADR-007. … Données Canada Central", "note": "Le schéma en vigueur."},
    {"src": "Plan_Projet_NOVA_v3_12sept", "loc": "ligne P-02 : C3 = « Terminé », G3 = « Migration Canada requise »", "lines": [4,4], "quote": "A3=P-02 | B3=Architecture | C3=Terminé | … | G3=Migration Canada requise", "note": "Cohérent avec la migration terminée."},
    {"src": "Architecture_NOVA_v1", "loc": "page 1 : « v1 - 18 juillet 2026 », bloc « Données / East US »", "lines": [1,7], "quote": "Version initiale préparée avant la décision de localisation des données. … Données East US", "note": "Version dépassée (pour le contexte)."},
  ],
  "cross": "ADR, transcription de l'atelier, courriel du fournisseur, compte rendu de comité, schéma v2 et plan.",
  "uncertainty": "Pas de rapport de validation technique détaillé. La liste exacte des ressources migrées n'est pas documentée.",
 },
 {
  "id": "Q08",
  "question": "La sécurité est-elle acceptée? Distinguez livraison et validation.",
  "answer": "Non. LIVRAISON : Boréal a déployé un correctif pour SEC-210 (la journalisation des exports CSV administrateur est incomplète : la ligne EXPORT_CSV existe, mais sans objet ni résultat) sur l'environnement de validation le 19 septembre. Ses tests automatisés passent. VALIDATION : c'est Sophie Lambert qui accepte, et elle ne l'a pas fait. Le 19 sept. : « “déployé” != “accepté” ». Au comité du 26 sept. : « Nous n'avons pas encore donné l'acceptation sécurité de SEC-210 ». Re-test prévu, statut gardé EN VALIDATION le 26 septembre à 15 h 40. Le ticket est « Bloquante avant production ». Cette validation est la condition de go-live numéro 1. Le risque R-02 « Validation sécurité incomplète » est ouvert, avec une probabilité élevée.",
  "nuance": [
    "Le rapport de statut du 21 septembre dit « Sécurité VERT, Correctif SEC-210 livré ». Il confond livraison et acceptation (et il admet avoir été écrit avant la vérification des tickets). Le brouillon d'Alex (« la sécurité […] complétée ») reprend cette erreur. À corriger (voir C-03).",
    "Le défaut n'est pas une absence totale de journal : la connexion, la consultation et la déconnexion sont bien tracées. C'est l'événement d'export qui est incomplet (capture SEC-210_audit : objet « --- », résultat « --- »).",
    "Sophie avait demandé dès le 23 juillet de journaliser les actions administrateur, « surtout consultation et export ». Le 27 août, elle a rappelé qu'il faudrait le vérifier en situation réelle.",
  ],
  "evidence": [
    {"src": "SEC-210", "loc": "en-tête (Priorité « Bloquante avant production », Statut « EN VALIDATION ») et commentaires du 19 sept. 10:22, 19 sept. 14:05, 26 sept. 15:40 (lignes 23 à 25)", "lines": [23,25], "quote": "Boréal : Fix déployé sur l'environnement de validation. Pour nous c'est réglé. / Sophie : […] Ne pas fermer avant validation sécurité. / Sophie : Re-test planifié. Statut maintenu EN VALIDATION.", "note": "Livraison et validation, dans le ticket."},
    {"src": "SEC-210", "loc": "lignes 17 et 18 (Attendu / Observé)", "lines": [17,18], "quote": "Observé : une ligne EXPORT_CSV existe avec utilisateur et horodatage, mais l'objet (identifiant du dossier) et le résultat sont absents. […] Le défaut est une journalisation d'export incomplète, pas l'absence totale d'une ligne d'export.", "note": "Le défaut exact."},
    {"src": "SEC-210_audit", "loc": "capture, tableau du journal, ligne 14:04:08 EXPORT_CSV : Objet « --- », Résultat « --- »; encadré « Observation QA »", "lines": [6,8], "quote": "14:04:08 | np.admin | EXPORT_CSV | --- | ---", "note": "Preuve visuelle du défaut."},
    {"src": "E08_Correctif_journalisation", "loc": "courriel du 19 sept. 10:20, lignes 9 à 11", "lines": [9,11], "quote": "Le correctif pour SEC-210 est déployé en validation depuis ce matin. Nos tests automatisés passent et, pour nous, le problème est corrigé. Sophie, tu peux faire ton re-test", "note": "La livraison (fournisseur)."},
    {"src": "Teams_19sept_Securite", "loc": "ligne 5 (10:31)", "lines": [4,6], "quote": "On garde le ticket en validation jusqu'à notre re-test. « déployé » != « accepté » :)", "note": "La position de la sécurité (autre source)."},
    {"src": "M06_Transcript_Comite_26sept", "loc": "lignes 6 à 8 (10:01 à 10:03) et 11 (10:09)", "lines": [6,11], "quote": "Vous avez livré un fix. Nous n'avons pas encore donné l'acceptation sécurité de SEC-210.", "note": "État au dernier comité. Condition de go-live numéro 1."},
    {"src": "Rapport_Statut_21sept", "loc": "page 1, tableau Synthèse, ligne « Sécurité, VERT, Correctif SEC-210 livré »; « Commentaire de gestion »", "lines": [10,18], "quote": "Sécurité VERT Correctif SEC-210 livré […] Le rapport a été préparé avant la dernière vérification détaillée de certains tickets.", "note": "CONTRADICTION (C-03) : livré n'est pas accepté."},
    {"src": "Registre_Risques_29sept", "loc": "ligne R-02 : F3 = « Ouvert », C3 = « Élevée », G3 = « Re-test de SEC-210 avant go-live »", "lines": [4,4], "quote": "A3=R-02 | B3=Validation sécurité incomplète | C3=Élevée | D3=Élevé | E3=Sophie Lambert | F3=Ouvert", "note": "Le registre est cohérent avec le ticket."},
  ],
  "cross": "Ticket, capture, courriel du fournisseur, Teams sécurité, transcription du comité et registre. Le rapport de statut est écarté : c'est la sécurité qui décide, et les sources plus récentes le contredisent.",
  "uncertainty": "Date du re-test de Sophie inconnue (« planifié »). Résultat inconnu au 30 septembre.",
 },
 {
  "id": "Q09",
  "question": "L'accessibilité est-elle complétée? Identifiez ce qui reste à corriger.",
  "answer": "Non. Deux anomalies sont corrigées et validées par Mélissa Gagnon : ACC-301 (champ sans étiquette, le lecteur d'écran dit « edit blank »), fermé le 15 août après validation avec NVDA et VoiceOver; ACC-302 (contraste 2,1:1 du texte de statut), fermé le 20 août après un re-test à 5,3:1. Il reste ACC-303 (créé le 17 septembre, priorité Haute, OUVERT) : dans la fenêtre « Modifier le dossier », le focus clavier tourne entre les champs Nom et Commentaire, et la touche Tab n'atteint jamais le bouton « Enregistrer » (reproduit sur Chrome et Edge). Boréal l'a reproduit le 18 sept. : le composant de fenêtre retient le focus avec une liste d'éléments incomplète. Au 26 septembre : « Toujours ouvert. Correctif annoncé pour la prochaine build. » Mélissa le juge bloquant avant la production. Sa fermeture est la condition de go-live numéro 2 (risque R-04 ouvert).",
  "nuance": [
    "Le courriel de Boréal du 20 août (« Tout devrait maintenant être conforme ») ne parlait que des étiquettes et du contraste. Mélissa avait annoncé dès le 12 août un deuxième passage clavier sur les fenêtres (rappelé au comité du 27 août et au suivi du 18 sept.). Une correction annoncée par le fournisseur n'est pas une validation QA.",
    "Le rapport de statut du 21 septembre (« Accessibilité VERT, Correctifs appliqués ») est contredit par ACC-303, ouvert depuis le 17 septembre. Le brouillon d'Alex (« accessibilité complétée ») doit être corrigé (voir C-04).",
    "Les captures ACC-301_labels et ACC-302_contraste sont anciennes : elles ne prouvent pas que ces défauts sont encore là (ils sont fermés). La capture ACC-303_focus (Build 2026.09.17), elle, est confirmée par le commentaire du 26 sept.",
  ],
  "evidence": [
    {"src": "ACC-303", "loc": "en-tête (Priorité Haute, Statut OUVERT) et commentaires du 17 sept. 13:14, 18 sept. 09:50, 26 sept. 11:03 (lignes 14 à 16)", "lines": [14,16], "quote": "le bouton Enregistrer n'est jamais atteint avec Tab. […] Le composant modal intercepte le focus avec une liste d'éléments focusables incomplète. […] 26 sept 11:03 - Mélissa : Toujours ouvert. Correctif annoncé pour la prochaine build.", "note": "Ce qui reste à corriger."},
    {"src": "ACC-303_focus", "loc": "capture Build 2026.09.17, bouton « Enregistrer » encadré, note « Le focus clavier ne rejoint pas ce bouton »", "lines": [3,4], "quote": "Le focus clavier ne rejoint pas ce bouton", "note": "Preuve visuelle."},
    {"src": "M06_Transcript_Comite_26sept", "loc": "lignes 9 et 15 (10:05, 10:12)", "lines": [9,15], "quote": "Il reste ACC-303. La modale ne permet toujours pas d'atteindre Enregistrer au clavier. Pour moi c'est un bloquant d'accessibilité avant production. […] On vise le correctif ACC-303 dans la prochaine build.", "note": "État au dernier comité (autre source que le ticket)."},
    {"src": "ACC-301", "loc": "commentaire du 15 août (ligne 16)", "lines": [14,16], "quote": "15 août - Mélissa : Validé avec NVDA et VoiceOver. Fermé.", "note": "Corrigé et validé."},
    {"src": "ACC-302", "loc": "commentaires des 13, 18 et 20 août (lignes 14 à 16)", "lines": [14,16], "quote": "J'ai mesuré 2,1:1 […] 18 août - Boréal : Palette de statut corrigée. 20 août - Mélissa : Re-test OK à 5,3:1. Fermé.", "note": "Corrigé et validé."},
    {"src": "E04_Corrections_accessibilite", "loc": "courriel du 20 août 15:44, ligne 9, et citation du 12 août (ligne 16)", "lines": [9,16], "quote": "Tout devrait maintenant être conforme de notre côté. […] > Je veux aussi repasser les modales au clavier dans une prochaine build.", "note": "L'annonce du fournisseur ne couvre que les étiquettes et le contraste. Le passage clavier était déjà annoncé."},
    {"src": "M05_CR_Suivi_18sept", "loc": "ligne 10", "lines": [10,10], "quote": "Accessibilité : ACC-301 et ACC-302 sont fermés. Un scénario de navigation clavier sur modal doit encore être vérifié.", "note": "État d'ensemble au 18 sept."},
    {"src": "Rapport_Statut_21sept", "loc": "page 1, ligne « Accessibilité, VERT, Correctifs appliqués »", "lines": [12,12], "quote": "Accessibilité VERT Correctifs appliqués", "note": "CONTRADICTION (C-04) : ACC-303 est ouvert depuis le 17 sept."},
    {"src": "Registre_Risques_29sept", "loc": "ligne R-04 : F5 = « Ouvert », G5 = « Fermer ACC-303 »", "lines": [6,6], "quote": "A5=R-04 | B5=Accessibilité | … | F5=Ouvert | G5=Fermer ACC-303", "note": "Le registre est cohérent."},
  ],
  "cross": "Tickets ACC-301, 302 et 303, capture, transcription M06, suivi M05, courriel E04 et registre. Le rapport de statut est écarté : c'est la QA qui valide, et les sources plus récentes le contredisent.",
  "uncertainty": "Date de la « prochaine build » inconnue. Aucun autre scénario clavier en attente n'est documenté (seul ACC-303 est ouvert).",
 },
 {
  "id": "Q10",
  "question": "Quelles sont les trois conditions de go-live? Précisez les travaux manquants du runbook à partir de sa capture.",
  "answer": "Les trois conditions ont été fixées au comité de direction du 26 septembre par Nicolas Perron, et confirmées par Sophie, Mélissa et Olivier : 1) la sécurité valide SEC-210 (Sophie Lambert); 2) ACC-303 est fermé (Mélissa Gagnon, correctif Boréal dans la « prochaine build »); 3) le runbook est approuvé, avec la procédure de retour arrière (rollback) (Olivier Côté). Ce qui manque au runbook, d'après la capture OPS-601_runbook (« Version du 25 septembre ») : les étapes 1 à 3 sont « OK » (vérifier la santé des services, activer le mode maintenance, déployer la version approuvée); l'étape 4 « Procédure de retour arrière » est « TODO »; l'étape 5 « Validation fonctionnelle post-déploiement » est « À compléter ». Il manque donc le retour arrière ET la validation fonctionnelle après déploiement. Olivier veut en plus une procédure qu'une autre personne peut exécuter sans appeler l'équipe projet. Le 29 septembre, il n'avait toujours pas reçu la version finale.",
  "nuance": [
    "Le ticket OPS-601 ne nomme que le rollback (« au minimum ») et renvoie à la capture pour « une autre étape à compléter » : c'est l'étape 5. Les deux doivent être livrées pour que le runbook puisse être approuvé.",
    "Ces conditions reprennent les « critères de sécurité, accessibilité et exploitation » posés par Nicolas dès le 10 septembre (15:27) et résumés dans E09 (27 sept.). Olivier avait demandé dès le 10 septembre un runbook final « au moins quelques jours avant » la mise en production.",
    "Aucune des trois conditions n'a de date limite documentée : « à confirmer » pour les trois, avant le 22 octobre.",
  ],
  "evidence": [
    {"src": "M06_Transcript_Comite_26sept", "loc": "lignes 11 à 14 (10:09 à 10:10) et 16 (10:15)", "lines": [11,16], "quote": "Donc trois conditions concrètes : validation sécurité de SEC-210, fermeture de ACC-303 et approbation du runbook incluant rollback. Exact? Sophie : Oui. Mélissa : Oui. Olivier : Oui.", "note": "Les conditions, telles que fixées."},
    {"src": "OPS-601_runbook", "loc": "capture « Version du 25 septembre », lignes 4 « Procédure de retour arrière : TODO » et 5 « Validation fonctionnelle post-déploiement : À compléter »", "lines": [6,7], "quote": "4. Procédure de retour arrière : TODO / 5. Validation fonctionnelle post-déploiement : À compléter", "note": "Les travaux manquants (la preuve demandée)."},
    {"src": "OPS-601", "loc": "commentaires des 25, 26 et 29 sept. (lignes 14 à 16)", "lines": [14,16], "quote": "Il manque au minimum la procédure de rollback. La capture jointe identifie aussi une autre étape à compléter. J'ai besoin de quelque chose qu'une autre personne peut exécuter sans appeler l'équipe projet. […] 29 sept - Olivier : Toujours pas reçu la version finale.", "note": "L'exigence de l'exploitation et l'état au 29 sept."},
    {"src": "E09_Rappel_mise_en_production", "loc": "courriel du 27 sept., ligne 11", "lines": [11,11], "quote": "conditionnelle aux validations restantes : sécurité, accessibilité et préparation exploitation. Le comité du 26 septembre a précisé les éléments à fermer.", "note": "Confirmation écrite (autre source)."},
    {"src": "M06_Transcript_Comite_26sept", "loc": "ligne 10 (10:07)", "lines": [10,10], "quote": "Le runbook est encore incomplet. Il manque le rollback. Je ne donnerai pas mon go exploitation tant que je n'ai pas une procédure exécutable.", "note": "C'est Olivier Côté qui décide."},
    {"src": "M04_Transcript_Comite_direction_10sept", "loc": "ligne 12 (15:12)", "lines": [12,12], "quote": "je veux un runbook final au moins quelques jours avant.", "note": "Contrainte de délai (sans chiffre)."},
    {"src": "Registre_Risques_29sept", "loc": "lignes R-02, R-03, R-04 (F3 à F5 = « Ouvert »)", "lines": [4,6], "quote": "R-02 Validation sécurité incomplète … R-03 Préparation exploitation incomplète … Finaliser le runbook et le rollback … R-04 Accessibilité … Fermer ACC-303", "note": "Les trois conditions correspondent aux trois risques ouverts."},
  ],
  "cross": "Transcription M06, capture du runbook, ticket OPS-601, courriel E09 et registre de risques.",
  "uncertainty": "Pas de date de livraison du runbook final ni de date du re-test. « Quelques jours avant » n'est pas chiffré.",
 },
]
