# -*- coding: utf-8 -*-
"""Registre des décisions : qui propose, qui décide, qui confirme."""

DECISIONS = [
 {"id": "D-01", "title": "Date de mise en production : 22 octobre 2026 (au lieu du 15)", "status": "Approuvée, sous conditions",
  "proposition": {"who": "Julien Moreau (Boréal)", "when": "8 sept. 2026, 11:16 (répétée le 10 sept. à 15:02)", "src": "E05_Retard_integration", "lines": [9,13]},
  "decision": {"who": "Comité de direction NOVA. Formulée par Élodie Caron", "when": "10 sept. 2026, 15:22 à 15:25", "src": "M04_Transcript_Comite_direction_10sept", "lines": [17,23]},
  "validation": {"who": "Confirmée par Nicolas (Teams 15 sept., E09 27 sept.), par le suivi du 18 sept. et par le comité du 26 sept.", "when": "15 au 27 sept.", "src": "E09_Rappel_mise_en_production", "lines": [9,13]},
  "why": "Connecteur interne (INT-101) : temps perdu, pas assez de marge pour stabiliser; reprise des tests intégrés; ne pas raccourcir les tests de sécurité et d'accessibilité; pas de pénalité au contrat.",
  "conditions": "Trois conditions de go-live (D-07). Pas un go automatique (M04 15:27).",
  "docs_to_update": "Plan projet (v3 toujours au 15 octobre), communications."},
 {"id": "D-02", "title": "Hébergement des données de production : Canada Central", "status": "Acceptée. Mise en œuvre vérifiée",
  "proposition": {"who": "Sophie Lambert (sécurité), comme exigence", "when": "22 juil. 2026 (courriel), 23 juil. 09:06 (atelier)", "src": "E02_Question_hebergement", "lines": [9,11]},
  "decision": {"who": "Atelier architecture (Élodie, Marc, Sophie, Julien). ADR-007", "when": "23 juil. 2026, 09:10 à 09:12", "src": "M02_Transcript_Architecture_23juillet", "lines": [11,17]},
  "validation": {"who": "Boréal (migration terminée, 26 août), puis comité du 27 août (vérifiée par l'équipe architecture)", "when": "26 et 27 août 2026", "src": "M03_CR_Comite_27aout", "lines": [5,5]},
  "why": "Les données de production doivent rester au Canada. Pour la sécurité, ce n'est « pas juste une préférence ».",
  "conditions": "ADR-007 : une validation technique avant les tests de production.",
  "docs_to_update": "Architecture v1 dépassée; v2 en vigueur."},
 {"id": "D-03", "title": "Authentification : SSO seulement en production", "status": "Décidée",
  "proposition": {"who": "Marc Gervais (question)", "when": "23 juil. 09:14", "src": "M02_Transcript_Architecture_23juillet", "lines": [18,18]},
  "decision": {"who": "Sophie Lambert (sécurité), confirmé par Boréal", "when": "23 juil. 09:15 à 09:17", "src": "M02_Transcript_Architecture_23juillet", "lines": [19,20]},
  "validation": {"who": "Résumé de l'atelier (09:43)", "when": "23 juil.", "src": "M02_Transcript_Architecture_23juillet", "lines": [30,30]},
  "why": "Exigence de la sécurité. C'était déjà prévu par Boréal.", "conditions": "", "docs_to_update": ""},
 {"id": "D-04", "title": "CR-01, rapports avancés et export de synthèse : +24 000 $", "status": "Approuvée",
  "proposition": {"who": "Boréal (demande de changement)", "when": "avant le 14 août 2026 (date non précisée)", "src": "CR-01_Rapports_avances_APPROUVE", "lines": [2,3]},
  "decision": {"who": "Comité de projet", "when": "14 août 2026", "src": "CR-01_Rapports_avances_APPROUVE", "lines": [5,12]},
  "validation": {"who": "Facturée sur INV-002 et payée", "when": "31 août 2026", "src": "INV-002", "lines": [14,23]},
  "why": "Ajout de rapports avancés, hors portée de départ.", "conditions": "Aucun changement de date annoncé.", "docs_to_update": "Montant autorisé : 204 000 $."},
 {"id": "D-05", "title": "CR-04, optimisation mobile avancée (18 000 $) : NON approuvée, reportée en phase 2", "status": "Refusée pour la phase 1. La demande reste un brouillon",
  "proposition": {"who": "Boréal (Julien Moreau)", "when": "4 sept. 2026 (brouillon); estimation évoquée au comité du 10 sept. à 15:35", "src": "CR-04_Optimisation_mobile_BROUILLON", "lines": [6,15]},
  "decision": {"who": "Comité du 10 sept. : « aucune approbation aujourd'hui ». Nicolas Perron (chargé de projet) : reporté en phase 2", "when": "10 sept. 15:37, puis 24 sept. 2026", "src": "E10_Fonction_mobile", "lines": [9,11]},
  "validation": {"who": "Document de décision de portée; rappel au comité du 26 sept. (« Facturer du CR-04, non »)", "when": "24 au 26 sept.", "src": "Decision_Portee_Phase2", "lines": [3,6]},
  "why": "Hors portée de la phase 1 (charte, contrat, compte rendu de démarrage). Ne pas mélanger avec les corrections d'accessibilité obligatoires.",
  "conditions": "Aucune dépense CR-04 engagée ni facturée sans nouvelle approbation.", "docs_to_update": "INV-003 à corriger (ligne de 18 000 $)."},
 {"id": "D-06", "title": "Changement de chargé de projet : Élodie Caron, puis Nicolas Perron", "status": "En vigueur depuis le 16 septembre 2026",
  "proposition": {"who": "« Comme convenu » : accord antérieur non documenté (le plan v3 du 12 sept. nomme déjà Nicolas sur P-06)", "when": "avant le 16 sept.", "src": "Plan_Projet_NOVA_v3_12sept", "lines": [8,8]},
  "decision": {"who": "Élodie Caron (annonce officielle)", "when": "16 sept. 2026, 08:35", "src": "E06_Transition_charge_projet", "lines": [9,11]},
  "validation": {"who": "Note de transition; rappel Teams; Nicolas anime les comités suivants", "when": "16 sept. et après", "src": "Note_transition_Elodie_16sept", "lines": [4,10]},
  "why": "Non documenté.", "conditions": "Élodie reste disponible quelques jours.", "docs_to_update": "Charte v1 (pas mise à jour, c'est voulu)."},
 {"id": "D-07", "title": "Trois conditions de go-live pour le 22 octobre", "status": "Décidée. Aucune condition remplie au 30 sept.",
  "proposition": {"who": "Nicolas Perron (10 sept. 15:27 : critères sécurité, accessibilité, exploitation), puis synthèse au comité", "when": "10 sept., puis 26 sept. 10:09", "src": "M04_Transcript_Comite_direction_10sept", "lines": [24,24]},
  "decision": {"who": "Comité de direction (Nicolas; confirmé par Sophie, Mélissa, Olivier)", "when": "26 sept. 2026, 10:09 à 10:16", "src": "M06_Transcript_Comite_26sept", "lines": [11,16]},
  "validation": {"who": "Courriel E09 à toute l'équipe", "when": "27 sept. 2026, 17:02", "src": "E09_Rappel_mise_en_production", "lines": [9,13]},
  "why": "Sécurité : SEC-210 pas encore accepté. Accessibilité : ACC-303 bloquant. Exploitation : runbook sans retour arrière.",
  "conditions": "1) validation sécurité SEC-210 (Sophie); 2) fermeture ACC-303 (Mélissa); 3) approbation du runbook avec rollback (Olivier).", "docs_to_update": "Compte rendu du 26 sept. annoncé par Nicolas (absent du dossier)."},
 {"id": "D-08", "title": "Correction des doublons de migration : clé d'idempotence sur external_request_id", "status": "Faite et validée (DATA-401 fermé)",
  "proposition": {"who": "Analyse DATA-401", "when": "2 sept. 2026", "src": "DATA-401", "lines": [13,16]},
  "decision": {"who": "Équipe migration (Camille Beaulieu)", "when": "sept. 2026", "src": "DATA-401", "lines": [16,16]},
  "validation": {"who": "Rejeu de 15 000 événements sans doublon; confirmé au comité du 10 sept.", "when": "9 sept. 2026", "src": "DATA-401", "lines": [18,19]},
  "why": "Les dossiers 8401 et 8402 étaient créés en double (deux messages Kafka presque en même temps).", "conditions": "", "docs_to_update": "Registre R-05 fermé (cohérent)."},
]
