# -*- coding: utf-8 -*-
"""Couche de métadonnées : date de référence, personnes, lecture de chaque source (rôle, qui décide), transcriptions vérifiées des captures."""

REFERENCE_DATE = "2026-09-30T09:00:00-04:00"
REFERENCE_DATE_LABEL = "30 septembre 2026, 9 h (heure de Montréal)"

PEOPLE = [
    {"name": "Nicolas Perron", "org": "Organisation Démo", "role": "Chargé de projet NOVA depuis le 16 septembre 2026. Il anime les comités depuis cette date.", "src": ["E06_Transition_charge_projet", "Note_transition_Elodie_16sept"]},
    {"name": "Élodie Caron", "org": "Organisation Démo", "role": "Chargée de projet du 7 juillet au 15 septembre 2026. C'est elle qui a formulé la décision du 10 septembre. Elle reste disponible quelques jours pour la transition.", "src": ["Charte_Projet_NOVA_v1", "E06_Transition_charge_projet"]},
    {"name": "Marc Gervais", "org": "Organisation Démo", "role": "Architecture. Responsable du connecteur interne (INT-101) et du risque R-01.", "src": ["M01_CR_Demarrage_07juillet", "INT-101", "Registre_Risques_29sept"]},
    {"name": "Sophie Lambert", "org": "Organisation Démo", "role": "Sécurité. C'est elle qui accepte ou refuse SEC-210. Elle a exigé que les données restent au Canada.", "src": ["SEC-210", "M02_Transcript_Architecture_23juillet"]},
    {"name": "Mélissa Gagnon", "org": "Organisation Démo", "role": "QA et accessibilité. C'est elle qui valide les tickets ACC. Responsable des tests intégrés (P-04).", "src": ["ACC-303", "Plan_Projet_NOVA_v3_12sept"]},
    {"name": "Olivier Côté", "org": "Organisation Démo", "role": "Exploitation. C'est lui qui donne le go exploitation et approuve le runbook (OPS-601, P-05, R-03).", "src": ["OPS-601", "M06_Transcript_Comite_26sept"]},
    {"name": "Camille Beaulieu", "org": "Organisation Démo", "role": "Migration des données (DATA-401, R-05).", "src": ["DATA-401", "Registre_Risques_29sept"]},
    {"name": "Amélie Fortin", "org": "Organisation Démo, Finances", "role": "Valide les factures. Elle retient INV-003 tant qu'elle n'a pas l'approbation de CR-04.", "src": ["E07_Facture_003_question"]},
    {"name": "Alex Deschamps", "org": "Organisation Démo, Communications", "role": "Prépare les messages de statut. Son brouillon du 21 septembre est à corriger.", "src": ["E11_Communication_statut", "Teams_15sept_ProjetNOVA"]},
    {"name": "Julien Moreau", "org": "Boréal Numérique Inc. (fournisseur)", "role": "Contact du fournisseur : architecture, correctifs, proposition de report, demande CR-04.", "src": ["E05_Retard_integration", "CR-04_Optimisation_mobile_BROUILLON"]},
]

# Comment lire chaque source : son rôle et qui a le pouvoir de décider.
SOURCE_META = {
    "README": {"role": "consigne", "authority": "Consignes du défi (pas une pièce du projet)"},
    "MANIFEST": {"role": "inventaire", "authority": "Liste des fichiers"},
    "E01_Lancement_NOVA": {"role": "primaire", "authority": "Chargée de projet. Confirme le démarrage."},
    "E02_Question_hebergement": {"role": "primaire", "authority": "Sécurité. Pose l'exigence, avant la décision du 23 juillet."},
    "E03_Confirmation_Canada_Central": {"role": "primaire", "authority": "Fournisseur. Dit que la migration est finie (à croiser avec M03)."},
    "E04_Corrections_accessibilite": {"role": "primaire", "authority": "Fournisseur. Une correction annoncée n'est pas une validation QA."},
    "E05_Retard_integration": {"role": "primaire", "authority": "Fournisseur. C'est une PROPOSITION, pas une décision (il le dit lui-même)."},
    "E06_Transition_charge_projet": {"role": "primaire", "authority": "Chargée de projet sortante. Annonce officielle du changement de responsable."},
    "E07_Facture_003_question": {"role": "primaire", "authority": "Finances. Question avant de payer une facture."},
    "E08_Correctif_journalisation": {"role": "primaire", "authority": "Fournisseur. Un correctif livré n'est pas une acceptation sécurité."},
    "E09_Rappel_mise_en_production": {"role": "primaire", "authority": "Chargé de projet. Rappel officiel : la date dépend de conditions."},
    "E10_Fonction_mobile": {"role": "primaire", "authority": "Chargé de projet. Fixe la portée (mobile en phase 2) et interdit de facturer CR-04."},
    "E11_Communication_statut": {"role": "primaire", "authority": "Communications. BROUILLON basé sur le rapport du 21 sept. À corriger."},
    "E12_Resolution_integration": {"role": "primaire", "authority": "Architecture. Confirme côté client que INT-101 est fermé."},
    "M01_CR_Demarrage_07juillet": {"role": "primaire", "authority": "Compte rendu de démarrage. Décisions de départ."},
    "M02_Transcript_Architecture_23juillet": {"role": "primaire", "authority": "Transcription. Décision Canada Central prise ensemble en atelier."},
    "M03_CR_Comite_27aout": {"role": "primaire", "authority": "Comité projet. Vérifie la migration. État de fin août."},
    "M04_Transcript_Comite_direction_10sept": {"role": "primaire", "authority": "Comité de direction. C'est ici que le 22 octobre est APPROUVÉ. C'est l'instance qui décide."},
    "M05_CR_Suivi_18sept": {"role": "primaire", "authority": "Suivi livraison. État d'ensemble au 18 sept."},
    "M06_Transcript_Comite_26sept": {"role": "primaire", "authority": "Comité de direction. Fixe les trois conditions de go-live. Source la plus récente."},
    "ACC-301": {"role": "primaire", "authority": "Ticket QA. Fermé le 15 août (validé NVDA et VoiceOver)."},
    "ACC-301_labels": {"role": "capture", "authority": "Capture ancienne (Test accessibilité). Le défaut est corrigé depuis."},
    "ACC-302": {"role": "primaire", "authority": "Ticket QA. Fermé le 20 août (5,3:1)."},
    "ACC-302_contraste": {"role": "capture", "authority": "Capture ancienne (Build 2026.08.12). Le défaut est corrigé depuis."},
    "ACC-303": {"role": "primaire", "authority": "Ticket QA. OUVERT, priorité haute. Dernier commentaire le 26 sept."},
    "ACC-303_focus": {"role": "capture", "authority": "Capture Build 2026.09.17. Le défaut est toujours ouvert au 26 sept. (voir le ticket)."},
    "DATA-401": {"role": "primaire", "authority": "Ticket migration. Fermé le 9 sept."},
    "DATA-401_doublons": {"role": "capture", "authority": "Capture ancienne, lot MIG-09-02. Corrigé depuis."},
    "DATA-401_echantillon": {"role": "pièce jointe", "authority": "Extrait CSV des doublons (même preuve que la capture)."},
    "INT-101": {"role": "primaire", "authority": "Ticket intégration. Fermé le 17 sept., validé par Marc Gervais."},
    "INT-101_aucun_resultat": {"role": "capture", "authority": "Capture ancienne (environnement intégration). Corrigé depuis."},
    "INT-101_extrait_logs": {"role": "pièce jointe", "authority": "Logs : erreur 401 le 5 sept., réponse 200 OK le 17 sept."},
    "OPS-601": {"role": "primaire", "authority": "Ticket exploitation. OUVERT. Olivier Côté donne le go exploitation."},
    "OPS-601_runbook": {"role": "capture", "authority": "Capture « Version du 25 septembre ». Dernier état connu du runbook."},
    "PERF-501": {"role": "primaire", "authority": "Ticket performance. Fermé le 7 sept."},
    "PERF-501_lenteur": {"role": "capture", "authority": "Capture ancienne. Corrigé depuis (620 ms)."},
    "SEC-210": {"role": "primaire", "authority": "Ticket sécurité. EN VALIDATION. Sophie Lambert décide de l'acceptation."},
    "SEC-210_audit": {"role": "capture", "authority": "Capture en environnement de validation. Montre le défaut (ligne EXPORT_CSV incomplète)."},
    "Charte_Projet_NOVA_v1": {"role": "primaire", "authority": "Charte v1 (7 juillet). Point de départ. Elle dit elle-même qu'elle n'est PAS mise à jour après les décisions."},
    "Note_transition_Elodie_16sept": {"role": "primaire", "authority": "Note de transition. Consignes de la chargée sortante."},
    "Plan_Projet_NOVA_v2": {"role": "primaire", "authority": "Plan v2. Avant la décision du 10 sept."},
    "Plan_Projet_NOVA_v3_12sept": {"role": "primaire", "authority": "Plan v3 (12 sept.). PÉRIMÉ sur la date : il n'a pas intégré la décision du 10 sept."},
    "Rapport_Statut_21sept": {"role": "primaire", "authority": "Rapport de statut. Auteur inconnu. Il admet avoir été écrit avant de vérifier les tickets. Ses « VERT » sécurité et accessibilité sont faux."},
    "Registre_Risques_29sept": {"role": "primaire", "authority": "Registre de risques (29 sept.). R-01 est périmé (suivi au 9 sept.). R-02 à R-04 sont justes."},
    "CONTRAT_Boreal_NOVA": {"role": "primaire", "authority": "Contrat. Fait foi pour le montant maximal et la règle des changements."},
    "CR-01_Rapports_avances_APPROUVE": {"role": "primaire", "authority": "Demande de changement APPROUVÉE (comité de projet, 14 août)."},
    "CR-04_Optimisation_mobile_BROUILLON": {"role": "primaire", "authority": "BROUILLON. Aucune approbation, aucune signature."},
    "INV-001": {"role": "primaire", "authority": "Facture payée."},
    "INV-002": {"role": "primaire", "authority": "Facture payée (inclut CR-01)."},
    "INV-003": {"role": "primaire", "authority": "Facture EN VALIDATION. Contient une ligne CR-04 non approuvée."},
    "ADR-007_Localisation_donnees": {"role": "primaire", "authority": "ADR acceptée. Décision formelle sur l'hébergement."},
    "Architecture_NOVA_v1": {"role": "primaire", "authority": "Schéma v1 (18 juillet, East US). DÉPASSÉ pour l'hébergement."},
    "Architecture_NOVA_v2": {"role": "primaire", "authority": "Schéma v2 (25 août, Canada Central). Version en vigueur."},
    "Decision_Portee_Phase2": {"role": "primaire", "authority": "Décision de portée (24 sept.). CR-04 reporté en phase 2."},
    "Teams_15sept_ProjetNOVA": {"role": "primaire", "authority": "Clavardage. Confirme que le plan n'a pas été corrigé."},
    "Teams_16sept_Transition": {"role": "primaire", "authority": "Clavardage. Rappel de la transition."},
    "Teams_19sept_Securite": {"role": "primaire", "authority": "Clavardage. « déployé » n'est pas « accepté »."},
    "Teams_22sept_Mobile": {"role": "primaire", "authority": "Clavardage. Désaccord sur la portée mobile."},
    "Courriel_archive_17sept": {"role": "doublon", "authority": "Copie exacte de E12. Ne compte pas comme une deuxième preuve."},
    "INV-778_Projet_ORION": {"role": "hors sujet", "authority": "Facture d'un AUTRE projet (ORION). Hors budget NOVA."},
    "Invitation_Formation_Excel": {"role": "hors sujet", "authority": "Rien à voir avec NOVA."},
    "Newsletter_Boreal_Septembre": {"role": "hors sujet", "authority": "Infolettre du fournisseur. Aucune valeur de preuve."},
    "Notes_personnelles_quelquun": {"role": "non officiel", "authority": "Notes personnelles, auteur inconnu. Aucun poids."},
    "Plan_NOVA_preliminaire_juin": {"role": "historique", "authority": "Plan préliminaire de juin, avant la charte. Dépassé."},
}

# Transcriptions vérifiées des captures (OCR corrigé à la main), pour l'affichage et la recherche.
SCREENSHOTS = {
    "ACC-301_labels": "Bandeau : NOVA, « Test accessibilité », https://nova.demo.local\nTitre : Formulaire de création\nSection : Créer une demande\nChamp texte avec seulement le texte d'exemple « Votre nom » (aucune étiquette visible)\nNote en rouge : « Le placeholder disparaît dès la saisie; aucun libellé associé n'est exposé. »",
    "ACC-302_contraste": "Bandeau : NOVA, « Build 2026.08.12 », https://nova.demo.local\nTitre : Portail NOVA\nÉlément : État de la demande (texte de statut bleu-gris sur fond pâle, contraste faible)\nNote : « Capture reçue avec le ticket : “le bleu/gris est bizarre” »",
    "ACC-303_focus": "Bandeau : NOVA, « Build 2026.09.17 », https://nova.demo.local\nTitre : Fenêtre de modification\nFenêtre « Modifier le dossier » : champ « Nom du demandeur » (valeur : Camille Roy), champ « Commentaire » (vide), bouton « Enregistrer » encadré en rouge\nNote en rouge sous le bouton : « Le focus clavier ne rejoint pas ce bouton »",
    "DATA-401_doublons": "Bandeau : NOVA, « Lot MIG-09-02 », https://nova.demo.local\nTitre : Résultats de migration\nTableau (ID | Demandeur | Courriel | Créé | Statut) :\n8401 | Alex Martin | alex.martin@example.org | 15:03:12 | Nouveau\n8402 | Alex Martin | alex.martin@example.org | 15:03:13 | Nouveau\n8403 | Sam Tremblay | sam.t@example.org | 15:04:01 | Nouveau\n(8401 et 8402 : même demandeur, même courriel, une seconde d'écart, donc un doublon)",
    "INT-101_aucun_resultat": "Bandeau : NOVA, « Environnement intégration », https://nova.demo.local\nTitre : Recherche de dossiers\nZone de résultats : « Aucun résultat »\nSous-texte : « Le ticket original contient seulement : “ça marche pas” »",
    "OPS-601_runbook": "Bandeau : NOVA, « Version du 25 septembre », https://nova.demo.local\nTitre : Runbook de mise en production\n1. Vérifier la santé des services : OK (vert)\n2. Activer le mode maintenance : OK (vert)\n3. Déployer la version approuvée : OK (vert)\n4. Procédure de retour arrière : TODO (rouge)\n5. Validation fonctionnelle post-déploiement : À compléter (rouge)",
    "PERF-501_lenteur": "Bandeau : NOVA, « Chrome - réseau entreprise », https://nova.demo.local\nTitre : Analyse de performance\nDOMContentLoaded : 2.4 s\nLargest Contentful Paint : 7.8 s (rouge)\nAPI /dossiers/search : 6.9 s (rouge)\nTransfert : 1.3 MB",
    "SEC-210_audit": "Bandeau : NOVA, « Environnement de validation », https://nova.demo.local\nTitre : Journal d'audit - administrateur\nTableau (Heure | Utilisateur | Action | Objet | Résultat) :\n14:02:10 | np.admin | LOGIN | Portail | SUCCÈS\n14:03:44 | np.admin | VIEW_RECORD | Dossier 8401 | SUCCÈS\n14:04:08 | np.admin | EXPORT_CSV | --- | ---   (objet et résultat absents)\n14:05:12 | np.admin | LOGOUT | Portail | SUCCÈS\nEncadré « Observation QA » : « Une exportation CSV a été effectuée à 14:04, mais aucun événement détaillé n'est visible. »",
}
