# -*- coding: utf-8 -*-
"""Contradictions résolues. basis : qui décide, date des faits, nature du document (ou une combinaison)."""

CONTRADICTIONS = [
 {"id": "C-01", "theme": "échéancier", "in_plan_or_register": True,
  "title": "Date de mise en production : 15 octobre (plan v3 du 12 sept., charte, plan v2) contre 22 octobre (comité du 10 sept.)",
  "a": {"claim": "P-06 Mise en production = 2026-10-15, note « Cible de planification »", "src": "Plan_Projet_NOVA_v3_12sept", "lines": [8,8], "loc": "cellules E7, F7, G7"},
  "b": {"claim": "« Le 22 devient la date officielle », approuvé par le comité de direction", "src": "M04_Transcript_Comite_direction_10sept", "lines": [17,23], "loc": "15:22 à 15:25"},
  "resolution": "Le 22 octobre l'emporte. Qui décide : le comité de direction a plus de poids qu'un document de planification. Dates : la décision (10 sept.) est plus récente que la charte (7 juil.) et que le plan v2. Le plan v3 (12 sept.) est postérieur à la décision, mais il ne l'a pas intégrée. Nicolas le constate sur Teams le 15 sept. (« le plan projet n'a visiblement pas encore été corrigé ») et la note de transition demande de « faire mettre à jour la date dans tous les plans ». La charte dit elle-même qu'elle n'est pas mise à jour après les décisions.",
  "basis": "qui décide + date des faits", "status_now": "Pas corrigée au 30 sept. Le plan v3 reste le dernier plan disponible. Voir l'action A-07.",
  "extra": [["Teams_15sept_ProjetNOVA", 5, 5], ["Note_transition_Elodie_16sept", 7, 7], ["Charte_Projet_NOVA_v1", 20, 20]]},
 {"id": "C-02", "theme": "intégration", "in_plan_or_register": True,
  "title": "Risque R-01 « Retard du connecteur interne » OUVERT dans le registre du 29 sept., alors que INT-101 est fermé et validé depuis le 17 sept.",
  "a": {"claim": "R-01 : Statut « Ouvert », commentaire « Suivi au 9 septembre 2026 »", "src": "Registre_Risques_29sept", "lines": [3,3], "loc": "cellules F2 et H2"},
  "b": {"claim": "« INT-101 est fermé. Le problème d'intégration qui avait déclenché le risque d'échéancier est considéré résolu. »", "src": "E12_Resolution_integration", "lines": [9,11], "loc": "courriel du 17 sept. 16:22"},
  "resolution": "Le ticket est fermé : la ligne R-01 est périmée. Date des faits : le fichier est daté du 29 sept., mais sa ligne R-01 n'a pas été revue depuis le 9 sept. (le commentaire le dit), alors que la fermeture date du 17 sept. (ticket, courriel du responsable architecture, suivi du 18 sept., logs 200 OK). Qui décide : le propriétaire du risque (Marc Gervais) est justement celui qui a validé la fermeture.",
  "basis": "date des faits + qui décide", "status_now": "Registre à corriger (fermer R-01). Voir l'action A-08. Une date de fichier récente ne garantit pas une information à jour.",
  "extra": [["INT-101", 17, 18], ["M05_CR_Suivi_18sept", 6, 6], ["INT-101_extrait_logs", 3, 3]]},
 {"id": "C-03", "theme": "sécurité", "in_plan_or_register": False,
  "title": "Sécurité « VERT, correctif livré » (rapport du 21 sept.) et « complétée » (brouillon d'Alex), contre SEC-210 EN VALIDATION, acceptation non donnée",
  "a": {"claim": "Sécurité VERT. Correctif SEC-210 livré", "src": "Rapport_Statut_21sept", "lines": [10,10], "loc": "tableau Synthèse, ligne Sécurité"},
  "b": {"claim": "« Vous avez livré un fix. Nous n'avons pas encore donné l'acceptation sécurité de SEC-210. »", "src": "M06_Transcript_Comite_26sept", "lines": [7,7], "loc": "10:02"},
  "resolution": "La sécurité n'est pas acceptée. Qui décide : Sophie Lambert (sécurité). Le rapport confond livraison (par le fournisseur, 19 sept.) et validation (par le client), et il reconnaît avoir été écrit « avant la dernière vérification détaillée de certains tickets ». Dates : les positions de Sophie du 19 sept. (14:05) et du 26 sept. (15:40), et le comité du 26 sept., sont plus récents que le rapport du 21 sept. Le registre du 29 sept. (R-02 ouvert, probabilité élevée) est cohérent avec le ticket.",
  "basis": "qui décide + date des faits", "status_now": "Rapport et brouillon de communication à corriger. Voir les actions A-09 et A-10.",
  "extra": [["SEC-210", 23, 25], ["Teams_19sept_Securite", 5, 5], ["E11_Communication_statut", 11, 13], ["Registre_Risques_29sept", 4, 4]]},
 {"id": "C-04", "theme": "accessibilité", "in_plan_or_register": False,
  "title": "Accessibilité « VERT, correctifs appliqués » (rapport du 21 sept.) et « conforme » (Boréal, 20 août), contre ACC-303 OUVERT (bloquant) depuis le 17 sept.",
  "a": {"claim": "Accessibilité VERT. Correctifs appliqués", "src": "Rapport_Statut_21sept", "lines": [12,12], "loc": "tableau Synthèse, ligne Accessibilité"},
  "b": {"claim": "« Il reste ACC-303. La modale ne permet toujours pas d'atteindre Enregistrer au clavier. Pour moi c'est un bloquant d'accessibilité avant production. »", "src": "M06_Transcript_Comite_26sept", "lines": [9,9], "loc": "10:05"},
  "resolution": "L'accessibilité n'est pas terminée. Qui décide : Mélissa Gagnon (QA et accessibilité) valide les tickets. Une correction annoncée par le fournisseur (E04, « tout devrait être conforme ») ne vaut pas validation, et elle ne portait que sur ACC-301 et 302. Dates : ACC-303 est créé le 17 sept., avant le rapport du 21 sept., et il est toujours ouvert le 26 sept. Les captures ACC-301 et 302 sont anciennes (défauts fermés les 15 et 20 août) et ne prouvent rien d'ouvert. La capture ACC-303 est confirmée par le ticket.",
  "basis": "qui décide + date des faits", "status_now": "ACC-303 ouvert. Condition de go-live numéro 2. Voir les actions A-02 et A-03.",
  "extra": [["ACC-303", 14, 16], ["E04_Corrections_accessibilite", 9, 16], ["M05_CR_Suivi_18sept", 10, 10], ["Registre_Risques_29sept", 6, 6]]},
 {"id": "C-05", "theme": "portée", "in_plan_or_register": False,
  "title": "Portée mobile : Boréal pense que l'optimisation mobile avancée est incluse (Teams 22 sept.) et la facture (INV-003), contre la portée de la phase 1 et la décision de report en phase 2",
  "a": {"claim": "« Je pensais que le mobile était inclus dans le scope initial, au moins l'optimisation avancée. » Plus la ligne « Optimisation interface mobile - CR-04 » de 18 000 $", "src": "Teams_22sept_Mobile", "lines": [4,4], "loc": "13:03"},
  "b": {"claim": "« les optimisations mobiles avancées proposées dans CR-04 ne font pas partie de la phase 1 approuvée. Nous les reportons à la phase 2. »", "src": "E10_Fonction_mobile", "lines": [9,11], "loc": "courriel du 24 sept."},
  "resolution": "Hors portée. Qui décide : le contrat (la portée incluse ne mentionne pas le mobile; tout travail hors portée demande une demande de changement écrite et approuvée), la charte v1, le compte rendu de démarrage (mobile avancé jamais discuté comme livrable), le comité du 10 sept. (aucune approbation) et la décision du chargé de projet (24 sept.). CR-04 est resté un brouillon. Seule la « compatibilité de base » mobile fait partie de la phase 1 (Nicolas, Teams 22 sept.).",
  "basis": "qui décide (contrat + gouvernance)", "status_now": "INV-003 à corriger (18 000 $). Voir l'action A-06.",
  "extra": [["CONTRAT_Boreal_NOVA", 18, 24], ["M01_CR_Demarrage_07juillet", 19, 20], ["M04_Transcript_Comite_direction_10sept", 30, 35], ["INV-003", 21, 21], ["CR-04_Optimisation_mobile_BROUILLON", 8, 15]]},
 {"id": "C-06", "theme": "gouvernance", "in_plan_or_register": True,
  "title": "Responsable du projet : Élodie Caron (charte v1, plan v2) contre Nicolas Perron (plan v3 du 12 sept., annonce du 16 sept.)",
  "a": {"claim": "Chargée de projet : Élodie Caron. P-06 responsable Élodie Caron", "src": "Charte_Projet_NOVA_v1", "lines": [4,4], "loc": "ligne 4; plan v2 cellule D7"},
  "b": {"claim": "« Nicolas Perron prend officiellement la charge du projet NOVA à compter d'aujourd'hui, 16 septembre. »", "src": "E06_Transition_charge_projet", "lines": [9,9], "loc": "courriel du 16 sept. 08:35"},
  "resolution": "Nicolas Perron, depuis le 16 septembre. Dates : l'annonce officielle, la note de transition et le rappel Teams (16 sept.) sont plus récents que la charte (7 juil.) et que le plan v2. Nature du document : la charte n'est pas mise à jour après les décisions (ligne 20). Petit écart : le plan v3 daté du 12 sept. nomme déjà Nicolas (D7). La transition avait donc été convenue avant l'annonce, mais la date officielle reste le 16 sept.",
  "basis": "date des faits + nature du document", "status_now": "Résolue.",
  "extra": [["Plan_Projet_NOVA_v3_12sept", 8, 8], ["Plan_Projet_NOVA_v2", 8, 8], ["Note_transition_Elodie_16sept", 4, 4]]},
 {"id": "C-07", "theme": "finances", "in_plan_or_register": False,
  "title": "Budget « VERT, sous le plafond contractuel » (rapport du 21 sept.) contre la facture INV-003 qui contient 18 000 $ non autorisés",
  "a": {"claim": "Budget VERT. Sous le plafond contractuel", "src": "Rapport_Statut_21sept", "lines": [8,8], "loc": "tableau Synthèse, ligne Budget"},
  "b": {"claim": "Ligne « Optimisation interface mobile - CR-04 » de 18 000 $ sur une facture en validation, sans approbation", "src": "INV-003", "lines": [21,21], "loc": "ligne CR-04"},
  "resolution": "Sur les chiffres, 186 000 $ facturés restent sous 204 000 $ (le rapport ne dit pas quel plafond il utilise; avec 180 000 $ on serait au-dessus). Mais ce « vert » cache une facturation non autorisée de 18 000 $. Qui décide : le contrat (changement écrit et approuvé obligatoire) et le chargé de projet (E10). Le bon statut budgétaire : sous le plafond, avec une facture contestée à régulariser.",
  "basis": "qui décide (contrat)", "status_now": "INV-003 retenue par Finances. Voir l'action A-06.",
  "extra": [["CONTRAT_Boreal_NOVA", 12, 24], ["E07_Facture_003_question", 9, 11], ["CR-01_Rapports_avances_APPROUVE", 6, 12]]},
 {"id": "C-08", "theme": "finances", "in_plan_or_register": False,
  "title": "INV-778 (41 000 $, 20 sept.) : même fournisseur, mais projet ORION. À exclure de NOVA",
  "a": {"claim": "Facture Boréal INV-778, 41 000 $, « Migration données - projet ORION »", "src": "INV-778_Projet_ORION", "lines": [10,24], "loc": "ligne Projet = ORION; note"},
  "b": {"claim": "Factures NOVA : INV-001, INV-002, INV-003 (champ Projet = NOVA)", "src": "INV-003", "lines": [10,10], "loc": "ligne Projet"},
  "resolution": "Nature du document : la facture indique « Projet : ORION » et une note « Cette facture concerne un autre projet ». Elle est rangée dans le dossier « documents connexes ». Rien à imputer à NOVA.",
  "basis": "nature du document", "status_now": "Exclue (piège du dossier).", "extra": []},
 {"id": "C-09", "theme": "échéancier", "in_plan_or_register": False,
  "title": "Notes personnelles non officielles (« vérifier si 15 oct encore date? probablement », « mobile nice to have ») contre les décisions documentées",
  "a": {"claim": "« vérifier si 15 oct encore date? probablement ». Auteur inconnu", "src": "Notes_personnelles_quelquun", "lines": [3,4], "loc": "lignes 3 et 4"},
  "b": {"claim": "Date officielle 22 octobre; mobile avancé hors phase 1", "src": "M04_Transcript_Comite_direction_10sept", "lines": [23,23], "loc": "15:25"},
  "resolution": "Aucun poids : notes personnelles, auteur inconnu, sans date. Les décisions de comité l'emportent. (De même, l'invitation à la formation Excel et l'infolettre Boréal ne disent rien sur NOVA.)",
  "basis": "qui décide", "status_now": "Écartée.", "extra": [["Invitation_Formation_Excel", 1, 3], ["Newsletter_Boreal_Septembre", 1, 2]]},
 {"id": "C-10", "theme": "architecture", "in_plan_or_register": False,
  "title": "Architecture v1 (East US) contre ADR-007 et architecture v2 (Canada Central)",
  "a": {"claim": "Données : East US (v1, 18 juillet)", "src": "Architecture_NOVA_v1", "lines": [1,7], "loc": "page 1"},
  "b": {"claim": "Données : Canada Central (v2, 25 août, révisée après ADR-007)", "src": "Architecture_NOVA_v2", "lines": [1,7], "loc": "page 1"},
  "resolution": "Dates et qui décide : l'ADR-007 (23 juillet, acceptée) remplace la v1 sur ce point, la v2 est plus récente et la migration a été vérifiée le 27 août. La pièce jointe de E02 (v1) et celle de E03 (v2) sont les mêmes fichiers que ceux du dossier 06 : pas de preuves supplémentaires.",
  "basis": "date des faits + qui décide", "status_now": "Résolue. La v1 est gardée comme historique.",
  "extra": [["ADR-007_Localisation_donnees", 9, 10], ["M03_CR_Comite_27aout", 5, 5]]},
]
